name: Spell Check

on: [push, pull_request]

jobs:
  spellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Spell Check All (w/ Codespell)
        uses: codespell-project/actions-codespell@master
        with:
         ignore-words-list: etc/codespell-ignore-words-list.txt
        #skip-paths: src/lib #not necessary since submodules are not pulled in

      - name: Spell Check Python (w/ PySpelling)
        uses: rojopolis/spellcheck-github-actions@0.30.0
        with:
         task_name: Python
